### ISSUE TITLE
请问如何查看1E记录以贡献数据？

### ISSUE THREAD

**Issue by zhouii** [domosekai/tripreader-data#4]
https://www.domosekai.com/reader/faq.html 的“调查方法介绍”中提及了TU刷卡都会有1E记录标注线路站点代码，我在舟山乘坐了公交车想贡献数据，但打开专家模式后没有看到，请问如何查找？有没有交流群可以交流？谢谢

![微信图片_20210823152841](https://user-images.githubusercontent.com/19874813/130408509-be97e55a-67f1-4b7e-a8c9-306b9f7cc95c.jpg)

**Comment by domosekai** [comment]
这种情况是卡机不写1E造成的。目前没有办法。
我们官网有个讨论组正在测试中，欢迎使用。
https://chat.domosekai.com

**Comment by zhouii** [comment]
我看标准文件，还有1A文件会记录交易信息，会不会有卡机写到1A？app能不能读取1A记录？
我也不是很懂，交流一下

![image](https://user-images.githubusercontent.com/19874813/130425299-b99325a5-ca35-43d1-86f2-b9c5d1ca92f0.png)

**Comment by domosekai** [comment]
您可以用票卡分析app读取1A，但公交卡机未必会写
