### ISSUE TITLE
ios系统bug反馈,tripreader在ios15系统中无法设置app语言

### ISSUE THREAD

**Issue by lxr760** [domosekai/tripreader-data#5]
tripreader在ios15系统中无法设置app语言。

点击setting--user interface后会跳转到app系统设置里，但里面并没有设置语言的地方

导致在系统英文状态下，无法单独把app设置成中文

![Snipaste_2022-01-06_10-37-38](https://user-images.githubusercontent.com/8476457/148319436-c603f4b2-6624-4f75-b626-5c5d4bf383fc.jpg)
![Snipaste_2022-01-06_10-37-52](https://user-images.githubusercontent.com/8476457/148319443-0c828e66-dc91-489d-9567-89c2ad32c8d3.jpg)

**Comment by domosekai** [comment]
This repo is not about the Trip Reader app.
